### ISSUE TITLE
Allow conventional commits handler configuration

### ISSUE THREAD

**Issue by TomerFi** [TomerFi/auto-me-bot#45]
### What did you have in mind?

Add the ability to configure the various handlers, to be more precise, [the conventional commits handler](https://github.com/TomerFi/auto-me-bot/blob/main/src/handlers/pr-conventional-commits.js) screams a lot about commit message length, especially for dependabot's commits in repos containing their own sub repos/projects.

Example:

![image](https://user-images.githubusercontent.com/28388442/180818232-28a1ea03-f731-4027-a2a5-b47e8ca5ec46.png)

**Comment by dolby360** [comment]
I'm trying :)

**Comment by TomerFi** [comment]
@dolby360 Thank you very much!
Here is what I was thinking about, and some pointers:

---

The handler already has a copy of the configuration, but it's not using it so I prefiixed the argument name with an underscore (`_config`) to avoid IDE warnings:
https://github.com/TomerFi/auto-me-bot/blob/2bbcda75d7a7e814414e8a415214ffb1a537353f/src/handlers/pr-conventional-commits.js#L23

So, any configuration keys we add, for example, `x`:
```
pr:
  conventionalCommits:
    x: y
```
should be instantly available, like so:
```
config.pr.conventionalCommits.x
```
---

This is where we load the configuration https://github.com/TomerFi/auto-me-bot/blob/2bbcda75d7a7e814414e8a415214ffb1a537353f/src/handlers/pr-conventional-commits.js#L36

[commitlint's JS configuration object](https://commitlint.js.org/#/reference-configuration?id=javascript)

---

[commitlint rules reference](https://commitlint.js.org/#/reference-rules)

Technically, for the example in the issue details, we only need the [body-max-line-length](https://commitlint.js.org/#/reference-rules?id=body-max-line-length),
but I think we should add support for any rule, something like:

```
pr:
  conventionalCommits:
    rules:
      - name: body-max-line-length
        rule: always
        value: 100
      - name: header-full-stop
        rule: never
        value: "."
      - name: header-max-length
        rule: always
        value: 72
```
