### ISSUE TITLE
Configuring the pr-signed-commits handler to ignore specific users

### ISSUE THREAD

**Issue by TomerFi** [TomerFi/auto-me-bot#58]
### What did you have in mind?

As suggested here https://github.com/TomerFi/auto-me-bot/issues/47#issuecomment-1211582631, adding a feature to allow configuring the `pr-signed-commits` to ignore specific users or emails, sounds like a great idea.

### Any lead on how this feature can be implemented?

Current `.github/auto-me-bot.yml` configuration for the `pr-signed-commits` handler is:

```yaml
---
pr:
  signedCommits:
```
We can add option to ignore a list of users/email or perhaps both:
```yaml
---
pr:
  signedCommits:
    ignore:
      users: ["dependabot[bot]", "anotheruser"]
      emails: ["support@github.com", "someother@email.moc"]
```
