### ISSUE TITLE
PR title enforcement 

### ISSUE THREAD

**Issue by dolby360** [TomerFi/auto-me-bot#89]
### What did you have in mind?

It seems like there is a [demand ](https://github.com/allero-io/allero/issues/105)to enforce conventional commits on PR titles as well.

### Any lead on how this feature can be implemented?

@TomerFi  suggested [here](https://github.com/allero-io/allero/issues/105#issuecomment-1271225209) on these 2 optional design.
```yaml
---
pr:
  conventionalCommits:
    includePrTitle: true
    rules:
      'body-max-line-length': [2, 'always', 150]
```
```yaml
---
pr:
  conventionalPrTitles:
  conventionalCommits:
    rules:
      'body-max-line-length': [2, 'always', 150]
```

I tend to agree with the second option. Because as the example shows it does not really make sense to custom rules the same way for both.

**Comment by TomerFi** [comment]
@dolby360 
Working on this, this should be quick.
I'm going with a new handler called _conventionalTitles_ and not a property in the existing handler _conventionalCommits_.
I think it makes more sense, users might want to only enforce title and not commits, or perhaps configure titles differently then commit messages.

The configuration will be quite identical to the existing handler (note _conventionalTitles_ as the handler name instead if the above mentioned _conventionalPrTitles_):

```yaml
---
pr:
  conventionalTitles:
    rules:
      'body-max-line-length': [2, 'always', 150]
  conventionalCommits:
    rules:
      'body-max-line-length': [2, 'always', 150]
```

Of course with default configuation, this will be:

```yaml
---
pr:
  conventionalTitles:
  conventionalCommits:
```
